### ISSUE TITLE
Update to pull from new storage location 

### ISSUE THREAD

**Issue by 0mniDreamer** [Streamerbot/sb-linux-installer#3]
going forward the streamer bot install files are located https://streamer.bot/api/releases/streamer.bot/latest  could we update the install.sh for it  please

**Comment by Corben78** [comment]
So far the [release list](https://api.github.com/repos/Streamerbot/Streamer.bot/releases) is sorted with latest first and gives the same result, which benefits does the latest url have?
Currently it would still be needed to parse the json result for the current url.

**Comment by 0mniDreamer** [comment]
i believe that all further release are going to be pulled from the the main streamer.bot API/site 
but if it works just the same them i guess there is no need :+1:
