### ISSUE TITLE
./install.sh: line 82: [: too many arguments

### ISSUE THREAD

**Issue by MichaelGame-Dev** [Streamerbot/sb-linux-installer#9]
I tried to run UNINSTALL=1 ./install.sh and I got this error.

```
./install.sh: line 82: [: too many arguments
cannot determine how to add /home/michael/.local/bin to /home/michael/.config/emacs/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by Whipstickgostop** [comment]
You should ensure that .local/bin is in your $PATH, the script is failing to add it for you

https://github.com/Streamerbot/sb-linux-installer?tab=readme-ov-file#paths

**Comment by MichaelGame-Dev** [comment]
> You should ensure that .local/bin is in your $PATH, the script is failing to add it for you
> 
> https://github.com/Streamerbot/sb-linux-installer?tab=readme-ov-file#paths

Thanks, I'll try this and see if it fixes the issue of not being able to launch in general. Otherwise, I'll try to uninstall after this change then reinstall and see if that helps at all.
